### ISSUE TITLE
Validator QA tracking

### ISSUE THREAD

**Issue by abought** [swcarpentry/DEPRECATED-lesson-template#114]
This issue exists to validate the validator. It will list QA steps and track bugs revealed by running the validator on all existing lesson repositories. Separate pull requests will be issued for each fix.

Bugs and questions are marked as checklist items.

These are the repos that will be checked using the latest version of the validator (presently #113, under review).
### Novice inflammation
- https://github.com/swcarpentry/matlab-novice-inflammation
- https://github.com/swcarpentry/python-novice-inflammation
- https://github.com/swcarpentry/r-novice-inflammation
### Version control
- https://github.com/swcarpentry/git-novice
- https://github.com/swcarpentry/hg-novice
### Other novice lessons
- https://github.com/swcarpentry/shell-novice
- https://github.com/swcarpentry/python-novice-turtles

**Comment by abought** [comment]
### Matlab novice inflammation

Markdown still being brought up to spec with current lesson template. Various YAML, link, and content restructuring recommended. (swcarpentry/matlab-novice-inflammation/issues/4)

Most errors seem reasonable and expected, as documented in previous external issue.
- [x] Bug: Anchor names were appearing in "file not found" errors- I've folded a fix for this into #113.

### Python novice inflammation

Repo is missing several files (motivation, reference, discussion.md). Some link changes needed.
- [ ] Question for @gvwilson : The spec calls for subheadings to be broken into separate topics, and the validator throws errors (eg `07-errors.md`) that recommend making a variety of extremely short pages instead. Perhaps this requirement should be relaxed?

### R novice inflammation

Various YAML, link, and markup changes needed to bring up to spec with template.
- [x] Bug: validator complains about a section being empty, when in fact it isn't present at all.
  `ERROR:root:In 08-making-packages-R.md: Learning Objectives should not be empty.`

**Comment by abought** [comment]
### Git novice

Fairly close to spec- YAML headers need updating, and some minor heading changes depending on question about subheadings raised above. 
- [x] Bug: Error message should wrap row name in single quotes.
  `ERROR:root:In ./02-collab.md: Header section is missing expected row subtitle`
- [x] Bug: some heading-related error messages are redundant in TopicPageValidator. Headings may need revision.

```
ERROR:root:In ./01-backup.md: Document contains heading not specified in the template: Setting Up
...
ERROR:root:In ./01-backup.md: The topic page should not have sub-headings outside of special blocks. If a topic needs sub-headings, it should be broken into multiple topics.
WARNING:root:In ./01-backup.md: The following sub-heading should be removed: Setting Up
```

### Hg novice

Index.md contains some broken links. Fairly close to spec- YAML headers need updating, and some minor heading changes depending on question about subheadings raised above. 

### Shell novice

Index.md contains some broken links.  Fairly close to spec. (headings, etc) License.md is out of date.

### Python novice turtles

Simple lesson, and very close to spec. Just needs a few link fixes.
- [x] Question: This lesson doesn't have several possible files (`instructors.md`, `motivation.md`, etc). Should there be an error message when possible files are omitted? How "minimal" can a lesson be in implementing the template?

**Comment by rgaiacs** [comment]
> Question: This lesson doesn't have several possible files (instructors.md, motivation.md, etc). Should there be an error message when possible files are omitted? How "minimal" can a lesson be in implementing the template?

A lesson must has a least:
- one file that match `[0-9][0-9]-[a-z]*\.md`
- `discussion.md`
- `index.md`
- `instructors.md`
- `LICENSE.md`
- `motivation.md`
- `README.md`
- `reference.md`

In the case of new lessons is OK that `discussion.md`, `instructors.md` and `reference.md` only have the YAML header.

**Comment by abought** [comment]
The issues found here have mostly been resolved, and new tickets have been created in lesson-specific repos. Closing.
